name: doc
on:
  push:
    branches:
    - devel
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Build static files
        shell: 'nix develop -c bash -e {0}'
        run: |
          make -C doc
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: README-WeiDU.html
