name: main
on:
  push:
    branches:
    - devel
  pull_request:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build-nix:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: '.#packages.aarch64-darwin'
            suffix: ''
          - os: macos-15-intel
            target: '.#packages.x86_64-darwin'
            suffix: ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - run: |
          nix build ${{ matrix.target }}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: result/WeiDU-Mac*.zip
          if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: fetch elkhound
        run: |
          mkdir -p bin
          curl -Lv https://github.com/The-Mod-Elephant/elkhound/releases/download/1.0.0/lin-elkhound -o bin/elkhound
          chmod +x bin/elkhound
          ls -ltrah bin/
          ./bin/elkhound
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.08.1+default-unsafe-string
      - name: build weidu
        run: |
          export PATH="$PATH:$PWD/bin"
          mkdir -p obj/x86_LINUX
          opam switch
          eval $(opam env)
          mv sample.Configuration Configuration
          make
          make linux_zip
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest
          path: WeiDU-Linux-*.zip
          if-no-files-found: error
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: fetch windows elkhound
        run: |
          curl -Lv https://github.com/The-Mod-Elephant/elkhound/releases/download/1.0.0/old-elkhound.exe -o elkhound.exe
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.4.14.2+options,ocaml-option-default-unsafe-string
      - name: Set-up Zip and Upx
        run: choco install upx zip
      - name: build weidu
        run: |
          mv elkhound.exe D:/a/weidu/weidu/_opam/bin/elkhound.exe
          opam switch
          (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
          mv sample.Configuration Configuration
          make
          make windows_zip
      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-latest
          path: WeiDU-Windows-*.zip
          if-no-files-found: error
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Build static files
        shell: 'nix develop -c bash -e {0}'
        run: |
          make -C doc
