name: tag
on:
  push:
    tags:
      - "*"
jobs:
  build-nix:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: '.#packages.aarch64-darwin'
            suffix: ''
          - os: ubuntu-latest
            target: '.#packages.x86_64-linux'
            suffix: ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - run: |
          nix build ${{ matrix.target }}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: result/bin/
  windows-build:
    runs-on: windows-2022
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - uses: actions/download-artifact@v5
        with:
          name: win-elkhound
          repository: The-Mod-Elephant/elkhound
          github-token: ${{ secrets.GH_TOKEN_CROSS_REPO_DOWNLOAD }}
          run-id: 19432082177
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.4.14.2+options,ocaml-option-default-unsafe-string
      - run: |
          mv elkhound.exe D:/a/weidu/weidu/_opam/bin/elkhound.exe
          opam switch
          (& opam env) -split '\r?\n' | ForEach-Object { Invoke-Expression $_ }
          mv sample.Configuration Configuration
          make
      - uses: actions/upload-artifact@v4
        with:
          name: windows-latest
          path: weidu.asm.exe
  release:
    name: release
    permissions:
      contents: write
    needs: [build-nix, windows-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: download linux artifact
        uses: actions/download-artifact@main
        with:
          name: ubuntu-latest
          path: linux
      - name: download mac artifact
        uses: actions/download-artifact@main
        with:
          name: macos-latest
          path: macos
      - name: download windows artifact
        uses: actions/download-artifact@main
        with:
          name: windows-latest
          path: windows
      - run: |
          mv linux/weidu.asm.exe lin-weidu
          mv macos/weidu.asm.exe mac-weidu
          mv windows/weidu.asm.exe weidu.exe
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        with:
          generateReleaseNotes: true
          artifacts: "lin-weidu,mac-weidu,weidu.exe"
