name: tag
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: docker.io/ocaml/opam:debian-ocaml-4.08
      options: --user root
    steps:
      - name: setup env
        run: |
          sudo apt-get install -yqqq bison wget flex git cmake
      - name: build elkhound
        run: |
          git clone https://github.com/The-Mod-Elephant/elkhound /home/opam/elkhound
          cd /home/opam/elkhound
          mkdir -p ${ELKHOUND_BUILD_DIR}
          export PATH=/home/opam/.opam/4.08/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          cmake -Wno-dev -S ${ELKHOUND_SRC_DIR} -B ${ELKHOUND_BUILD_DIR} -D CMAKE_BUILD_TYPE=Release
          make -C ${ELKHOUND_BUILD_DIR}
          mv /home/opam/elkhound/build/elkhound/elkhound /usr/bin/.
        env:
          ELKHOUND_BUILD_DIR: "build"
          ELKHOUND_SRC_DIR: "src"
      - name: build weidu
        run: |
          git clone https://github.com/${{ github.repository }} -b ${{ github.head_ref || github.ref_name }} /home/opam/weidu
          cd /home/opam/weidu
          mv .github/scripts/Configuration .
          make
          mv weidu.asm.exe weidu-linux
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: /home/opam/weidu/weidu-linux
  release:
    name: release
    permissions:
      contents: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: linux
          path: linux
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        with:
          generateReleaseNotes: true
          artifacts: "linux/weidu-linux"
