name: tag
on:
  push:
    tags:
      - "*"
jobs:
  build-nix:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: '.#packages.aarch64-darwin'
            suffix: ''
          - os: ubuntu-latest
            target: '.#packages.x86_64-linux'
            suffix: ''
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - run: |
          nix build ${{ matrix.target }}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: result/bin/
  release:
    name: release
    permissions:
      contents: write
    needs: [build-nix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@main
        with:
          name: ubuntu-latest
          path: linux
      - uses: actions/download-artifact@main
        with:
          name: macos-latest
          path: macos
      - run: |
          mv linux/weidu.asm.exe lin-weidu
          mv macos/weidu.asm.exe mac-weidu
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        with:
          generateReleaseNotes: true
          artifacts: "lin-weidu,mac-weidu"
